### ISSUE TITLE
5.6: Document the increased system requirements

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/woltlab.github.io#275]
- [x] PHP 8.1 (WoltLab/WCF#4782)
- [x] MySQL 8.0.29 / MariaDB 10.5.12 (WoltLab/WCF#4797)
- [x] x64 (WoltLab/WCF#4784)
- [x] es2019 (WoltLab/WCF#4783)
