### ISSUE TITLE
5.4: Add note about the upgrades of external libraries

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/woltlab.github.io#91]
- [x] Guzzle 7.2 (WoltLab/WCF#3619)
- [x] Emogrifier 5.0 (WoltLab/WCF#3738)
- [x] Constant Time Encoder
- [x] scssphp (WoltLab/WCF#3851)

**Comment by TimWolla** [comment]
This is resolved for now.
